name: 'publish'

on: workflow_dispatch

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04' 
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: download mesh-thumbnail (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          mkdir external-binaries
          cd external-binaries
          wget -O mesh-thumbnail-x86_64-unknown-linux-gnu https://github.com/suchmememanyskill/mesh-thumbnail/releases/latest/download/mesh-thumbnail
          chmod a+x mesh-thumbnail-x86_64-unknown-linux-gnu

      - name: download mesh-thumbnail (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          mkdir external-binaries
          cd external-binaries
          curl -L https://github.com/suchmememanyskill/mesh-thumbnail/releases/latest/download/mesh-thumbnail.exe -o mesh-thumbnail-x86_64-pc-windows-msvc.exe

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' 
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'Mesh Organiser v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}